alias lock='. ~/bin/lock.sh'
alias rain='. ~/bin/rain.sh'
alias j='java'
alias jc='javac'
alias gs='git status'
alias gb='git branch'
alias ls='ls --color=auto'
alias py2='python2'
alias emacs='emacs -nw'
